### ISSUE TITLE
Add social_links to person

### ISSUE THREAD

**Issue by dwayhs** [CWISoftware/enlighten#55]
Create new model:

SocialLink
  - person:references
  - provider:string
  - identifier:string

Methods
  - url: should read the url pattern from the configuration file and generate it based on the provider and identifier
  - available_providers: should return the providers based on the configuration file

Relations
  - user has_many :social_links
  - social_link belongs_to :user

Configuration file:
  - path: config/social_links.yml
 
Configuration file structure:

```
social_links:
  - provider: github
    url: https://github.com/#{identifier}
  - provider: twitter
    url: https://twitter.com/#{identifier}
```
